spring:
  application:
    name: ApiGateway

server:
  port: 9003

#
#  cloud:
#    gateway:
#      routes:
#        - id: USERSERVICE
#          uri: lb://USERSERVICE
#          predicates:
#            - Path=/users/**   # This path must match what the user service is expecting
#
#        - id: HOTELSERVICE
#          uri: lb://HOTELSERVICE
#          predicates:
#            - Path=/hotels/**   # This path must match what the hotel service is expecting
#
#        - id: RATINGSERVICE
#          uri: lb://RATINGSERVICE
#          predicates:
#            - Path=/ratings/**   # This path must match what the rating service is expecting

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

